version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "totodeltolosan"
    assignees:
      - "totodeltolosan"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/eve/cognitive"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/eve/simulation"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/eve/development"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/eve/interfaces"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
