site_name: AGI Constitutional Framework
site_description: Documentation du framework de développement AGI constitutionnel
site_url: https://totodeltolosan.github.io/AGI/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Constitutional Framework: architecture/constitutional.md
    - Compliance System: architecture/compliance.md
  - Development:
    - Getting Started: development/getting-started.md
    - Contribution Guidelines: development/contributing.md
    - Workflows: development/workflows.md
  - API Reference: api/

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - codehilite
