name: 🐛 Bug Report
description: Signaler un bug dans AGI-EVE
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - votre-username
body:
  - type: markdown
    attributes:
      value: |
        Merci de signaler ce bug ! Veuillez remplir les informations ci-dessous.
        
  - type: input
    id: component
    attributes:
      label: Composant affecté
      description: Quel module est concerné ? (core, eve, tools, etc.)
      placeholder: ex. core/cognitive
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: Description du bug
      description: Décrivez ce qui s'est passé
      placeholder: Décrivez le problème...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Étapes de reproduction
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '....'
        3. Voir l'erreur
    validations:
      required: true
