name: ✨ Feature Request
description: Proposer une nouvelle fonctionnalité
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème à résoudre
      description: Quel problème cette fonctionnalité résoudrait-elle ?
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Décrivez votre solution idéale
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considérées
      description: Avez-vous considéré d'autres solutions ?
