name: 🔍 GAIA Code Analysis Integration

on:
  push:
    paths: ['eve/development/code_analysis/**', '**/*.py']
  pull_request:
    paths: ['**/*.py']
  schedule:
    - cron: '0 */6 * * *'

jobs:
  gaia-analysis:
    name: GAIA PrometheusCore Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup GAIA Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install GAIA Dependencies
      run: |
        pip install ast-analyze code-complexity-tools
        pip install radon vulture bandit safety
        pip install tree-sitter-python pygments
        
    - name: GAIA PrometheusCore Integration Test
      run: |
        cd eve/development/code_analysis/
        
        echo "🔍 TEST GAIA PROMETHEUS CORE"
        python -c "
        try:
            from prometheus_core import PrometheusAnalyzer
            from code_hunter import CodeHunter
            
            # Initialiser GAIA
            prometheus = PrometheusAnalyzer()
            hunter = CodeHunter()
            
            print('✅ GAIA PrometheusCore: Initialisation OK')
            
            # Test analyse de code
            test_code = '''
def test_function():
    x = 1 + 1
    return x
'''
            analysis = prometheus.analyze_code(test_code)
            print('✅ GAIA: Analyse de code fonctionnelle')
            
        except Exception as e:
            print(f'⚠️ GAIA Integration: {e}')
            print('Note: Modules GAIA en migration')
        "
        
    - name: Run GAIA on Entire Codebase
      run: |
        echo "🔍 ANALYSE GAIA COMPLÈTE DU PROJET" > gaia-analysis.md
        echo "==================================" >> gaia-analysis.md
        echo "" >> gaia-analysis.md
        
        # Analyser avec outils disponibles
        echo "## 📊 Métriques Globales" >> gaia-analysis.md
        
        total_py_files=$(find . -name "*.py" -not -path "./.git/*" | wc -l)
        total_lines=$(find . -name "*.py" -not -path "./.git/*" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}' || echo "0")
        
        echo "- **Fichiers Python**: $total_py_files" >> gaia-analysis.md
        echo "- **Lignes totales**: $total_lines" >> gaia-analysis.md
        echo "" >> gaia-analysis.md
        
        # Complexité avec radon
        echo "## 🧮 Analyse Complexité (Radon)" >> gaia-analysis.md
        radon cc . -a -nc --total-average > radon_complexity.txt 2>/dev/null || echo "Analyse complexité en cours..." > radon_complexity.txt
        head -20 radon_complexity.txt >> gaia-analysis.md
        echo "" >> gaia-analysis.md
        
        # Code mort avec vulture
        echo "## 🔍 Code Inutilisé (Vulture)" >> gaia-analysis.md
        vulture . --min-confidence 80 | head -10 >> gaia-analysis.md 2>/dev/null || echo "Analyse code mort en cours..." >> gaia-analysis.md
        echo "" >> gaia-analysis.md
        
        # Sécurité avec bandit
        echo "## 🛡️ Analyse Sécurité (Bandit)" >> gaia-analysis.md
        bandit -r . -f txt | head -20 >> gaia-analysis.md 2>/dev/null || echo "Analyse sécurité en cours..." >> gaia-analysis.md
        
    - name: GAIA Integration with AGI Compliance
      run: |
        echo "" >> gaia-analysis.md
        echo "## 🤝 Intégration GAIA-AGI" >> gaia-analysis.md
        
        # Vérifier intégration avec système de conformité AGI
        if [ -f "core/compliance/audit_constitutionnel.py" ]; then
          echo "✅ **Audit Constitutionnel**: Détecté" >> gaia-analysis.md
          
          # Test intégration
          python -c "
          import sys
          sys.path.append('core/compliance')
          sys.path.append('eve/development/code_analysis')
          
          try:
              # Test import croisé
              from audit_constitutionnel import AuditeurConstitutionnel
              
              auditor = AuditeurConstitutionnel()
              print('✅ Intégration GAIA-AGI: Fonctionnelle')
              
              # Test analyse intégrée
              if hasattr(auditor, 'analyser_avec_gaia'):
                  print('✅ Méthode GAIA intégrée: Disponible')
              else:
                  print('⚠️ Méthode GAIA: À développer')
                  
          except Exception as e:
              print(f'⚠️ Intégration GAIA-AGI: {e}')
          " >> gaia-analysis.md
          
        else
          echo "⚠️ **Audit Constitutionnel**: Non trouvé" >> gaia-analysis.md
        fi
        
    - name: Upload GAIA Analysis
      uses: actions/upload-artifact@v3
      with:
        name: gaia-code-analysis
        path: |
          gaia-analysis.md
          radon_complexity.txt
