name: 🎮 UI Interface Validation

on:
  push:
    paths: ['eve/interfaces/**']
  pull_request:
    paths: ['eve/interfaces/**']
  schedule:
    - cron: '0 8 * * *'

jobs:
  ui-validation:
    name: UI/UX Interface Testing
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup UI Testing Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install UI Dependencies
      run: |
        pip install tkinter-modern customtkinter PyQt6
        pip install pytest-qt pytest-tkinter ui-testing
        sudo apt-get update
        sudo apt-get install -y xvfb x11-utils
        
    - name: Test EVE Interface Components
      run: |
        echo "🎮 VALIDATION INTERFACES EVE" > ui-report.md
        echo "============================" >> ui-report.md
        echo "" >> ui-report.md
        
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 2
        
        # Analyser interfaces EVE
        if [ -d "eve/interfaces" ]; then
          echo "## 🖥️ Interfaces Détectées" >> ui-report.md
          
          ui_modules=("ui" "logs" "documentation" "apis")
          
          for module in "${ui_modules[@]}"; do
            if [ -d "eve/interfaces/$module" ]; then
              file_count=$(find "eve/interfaces/$module" -name "*.py" | wc -l)
              echo "- **$module**: $file_count modules" >> ui-report.md
            else
              echo "- **$module**: ⚠️ Non trouvé" >> ui-report.md
            fi
          done
          echo "" >> ui-report.md
        fi
        
    - name: Tkinter Interface Testing
      run: |
        echo "" >> ui-report.md
        echo "## 🖼️ Test Interfaces Tkinter" >> ui-report.md
        echo "" >> ui-report.md
        
        export DISPLAY=:99
        
        python -c "
        import tkinter as tk
        import sys
        
        print('🖼️ Test interfaces Tkinter...')
        
        try:
            root = tk.Tk()
            root.title('AGI-EVE Interface Test')
            root.geometry('400x300')
            
            label = tk.Label(root, text='Interface EVE-AGI Test')
            label.pack(pady=10)
            
            button = tk.Button(root, text='Test Button')
            button.pack(pady=5)
            
            root.update()
            
            print('✅ Tkinter: Interface basique OK')
            
            root.destroy()
            print('✅ Cleanup: Interface fermée proprement')
            
        except Exception as e:
            print(f'❌ Erreur Tkinter: {e}')
            sys.exit(1)
        " >> ui-report.md
        
    - name: Upload UI Validation Report
      uses: actions/upload-artifact@v3
      with:
        name: ui-interface-validation
        path: ui-report.md
