name: "Ouvrier : Statisticien Lignes"

on:
  workflow_call:
    inputs:
      artefact_resultats_juges:
        description: "Artefact JSON des résultats du jugement"
        required: true
        type: string
      inclure_percentiles:
        description: "Inclure les percentiles dans les statistiques"
        required: false
        default: false
        type: boolean
      nom_artefact_sortie:
        description: "Nom de l'artefact de sortie"
        required: false
        default: "statistiques.json"
        type: string
    outputs:
      artefact_resultats:
        description: "Nom de l'artefact contenant les statistiques"
        value: ${{ jobs.calculer_statistiques.outputs.artefact_name }}
      taux_conformite:
        description: "Taux de conformité global calculé"
        value: ${{ jobs.calculer_statistiques.outputs.taux_conformite }}
      moyenne_lignes:
        description: "Moyenne de lignes par fichier"
        value: ${{ jobs.calculer_statistiques.outputs.moyenne_lignes }}
      validation_reussie:
        description: "Validation du résultat par le Qualiticien"
        value: ${{ jobs.validation_resultats.outputs.validation_success }}

jobs:
  calculer_statistiques:
    name: "Calcul des statistiques globales"
    runs-on: ubuntu-latest
    outputs:
      artefact_name: ${{ steps.stats.outputs.artefact_name }}
      taux_conformite: ${{ steps.stats.outputs.taux_conformite }}
      moyenne_lignes: ${{ steps.stats.outputs.moyenne_lignes }}
    
    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4
      
      - name: "Configuration Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: "Téléchargement des résultats du jugement"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact_resultats_juges }}
          path: ./input/
      
      - name: "Exécution du calcul statistique"
        id: stats
        run: |
          python .github/scripts/ouvrier_statisticien.py \
            --artefact-resultats-juges "./input/${{ inputs.artefact_resultats_juges }}" \
            --sortie "${{ inputs.nom_artefact_sortie }}" \
            ${{ inputs.inclure_percentiles && '--inclure-percentiles' || '' }}
          
          echo "artefact_name=${{ inputs.nom_artefact_sortie }}" >> $GITHUB_OUTPUT
          
          # Extraction des métriques clés
          python -c "import json; try:; with open('${{ inputs.nom_artefact_sortie }}', 'r') as f:; data = json.load(f); conformite = data.get('statistiques_conformite', {}); base = data.get('statistiques_base', {}); print(f'taux_conformite={conformite.get(\\"taux_conformite\\", 0):.1f}'); print(f'moyenne_lignes={base.get(\\"moyenne_lignes\\", 0):.1f}'); except Exception as e:; print('taux_conformite=0'); print('moyenne_lignes=0')" >> $GITHUB_OUTPUT
      
      - name: "Upload artefact statistiques"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.nom_artefact_sortie }}
          path: ${{ inputs.nom_artefact_sortie }}
          retention-days: 30

  validation_resultats:
    name: "Validation par Qualiticien"
    runs-on: ubuntu-latest
    needs: calculer_statistiques
    outputs:
      validation_success: ${{ steps.validate.outputs.validation_success }}
    
    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4
      
      - name: "Appel du Qualiticien de validation"
        id: validate
        uses: ./.github/workflows/05-03-lignes-valid-statisticien.yml
        with:
          artefact_statistiques: ${{ needs.calculer_statistiques.outputs.artefact_name }}
          mode_strict: true
