name: "Ouvrier : Conseiller Lignes"

on:
  workflow_call:
    inputs:
      artefact_statistiques:
        description: "Artefact JSON des statistiques"
        required: true
        type: string
      niveau_detail:
        description: "Niveau de détail des recommandations"
        required: false
        default: "detaille"
        type: string
      inclure_exemples:
        description: "Inclure des exemples de code"
        required: false
        default: true
        type: boolean
      nom_artefact_sortie:
        description: "Nom de l'artefact Markdown de sortie"
        required: false
        default: "recommandations.md"
        type: string
    outputs:
      artefact_resultats:
        description: "Nom de l'artefact contenant les recommandations"
        value: ${{ jobs.generer_conseils.outputs.artefact_name }}
      taille_document:
        description: "Taille du document généré en caractères"
        value: ${{ jobs.generer_conseils.outputs.taille_doc }}
      validation_reussie:
        description: "Validation du résultat par le Qualiticien"
        value: ${{ jobs.validation_resultats.outputs.validation_success }}

jobs:
  generer_conseils:
    name: "Génération des recommandations"
    runs-on: ubuntu-latest
    outputs:
      artefact_name: ${{ steps.advice.outputs.artefact_name }}
      taille_doc: ${{ steps.advice.outputs.taille_doc }}
    
    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4
      
      - name: "Configuration Python 3.11"
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: "Téléchargement des statistiques"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact_statistiques }}
          path: ./input/
      
      - name: "Validation niveau de détail"
        run: |
          niveau="${{ inputs.niveau_detail }}"
          case "$niveau" in
            base|detaille|expert)
              echo "✅ Niveau de détail valide : $niveau"
              ;;
            *)
              echo "❌ Niveau de détail invalide : $niveau"
              echo "Valeurs acceptées: base, detaille, expert"
              exit 1
              ;;
          esac
      
      - name: "Exécution du conseiller"
        id: advice
        run: |
          python .github/scripts/ouvrier_conseiller.py \
            --artefact-statistiques "./input/${{ inputs.artefact_statistiques }}" \
            --sortie "${{ inputs.nom_artefact_sortie }}" \
            --niveau-detail "${{ inputs.niveau_detail }}" \
            ${{ inputs.inclure_exemples && '--inclure-exemples' || '' }}
          
          echo "artefact_name=${{ inputs.nom_artefact_sortie }}" >> $GITHUB_OUTPUT
          
          # Calcul de la taille du document
          if [ -f "${{ inputs.nom_artefact_sortie }}" ]; then
            taille=$(stat -c%s "${{ inputs.nom_artefact_sortie }}")
            echo "taille_doc=$taille" >> $GITHUB_OUTPUT
            echo "✅ Document généré : $taille caractères"
          else
            echo "taille_doc=0" >> $GITHUB_OUTPUT
          fi
      
      - name: "Upload artefact recommandations"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.nom_artefact_sortie }}
          path: ${{ inputs.nom_artefact_sortie }}
          retention-days: 30

  validation_resultats:
    name: "Validation par Qualiticien"
    runs-on: ubuntu-latest
    needs: generer_conseils
    outputs:
      validation_success: ${{ steps.validate.outputs.validation_success }}
    
    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4
      
      - name: "Appel du Qualiticien de validation"
        id: validate
        uses: ./.github/workflows/05-05-lignes-valid-conseiller.yml
        with:
          artefact_recommandations: ${{ needs.generer_conseils.outputs.artefact_name }}
          taille_minimale: 500
