name: "Qualiticien : Validation Statisticien Lignes"

on:
  workflow_call:
    inputs:
      artefact_statistiques:
        description: "Nom de l'artefact JSON contenant les statistiques"
        required: true
        type: string
      mode_strict:
        description: "Activer le mode de validation strict"
        required: false
        default: true
        type: boolean
    outputs:
      validation_success:
        description: "Résultat de la validation (true/false)"
        value: ${{ jobs.validate_statisticien.outputs.success }}
      validation_errors:
        description: "Nombre d'erreurs de validation détectées"
        value: ${{ jobs.validate_statisticien.outputs.error_count }}

jobs:
  validate_statisticien:
    name: "Validation schéma statistiques"
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.validate.outputs.validation_success }}
      error_count: ${{ steps.validate.outputs.error_count }}
    
    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4
      
      - name: "Configuration Python 3.11"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: "Téléchargement de l'artefact à valider"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact_statistiques }}
          path: ./validation-input/
      
      - name: "Exécution de la validation du schéma"
        id: validate
        run: |
          echo "🔍 Validation du schéma 'statistiques'"
          
          if python .github/scripts/qualiticien_validation_schema.py \
            --artefact "./validation-input/${{ inputs.artefact_statistiques }}" \
            --schema-type "statistiques" \
            ${{ inputs.mode_strict && '--mode-strict' || '' }}; then
            
            echo "validation_success=true" >> $GITHUB_OUTPUT
            echo "error_count=0" >> $GITHUB_OUTPUT
            echo "✅ VALIDATION RÉUSSIE"
          else
            echo "validation_success=false" >> $GITHUB_OUTPUT
            echo "error_count=1" >> $GITHUB_OUTPUT
            echo "❌ VALIDATION ÉCHOUÉE"
            exit 1
          fi
