name: "Qualiticien : Validation Conseiller Lignes"

on:
  workflow_call:
    inputs:
      artefact_recommandations:
        description: "Nom de l'artefact Markdown contenant les recommandations"
        required: true
        type: string
      taille_minimale:
        description: "Taille minimale attendue en octets"
        required: false
        default: 50
        type: number
    outputs:
      validation_success:
        description: "Résultat de la validation (true/false)"
        value: ${{ jobs.validate_conseiller.outputs.success }}
      validation_errors:
        description: "Nombre d'erreurs de validation détectées"
        value: ${{ jobs.validate_conseiller.outputs.error_count }}

jobs:
  validate_conseiller:
    name: "Validation artefact recommandations Markdown"
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.validate.outputs.validation_success }}
      error_count: ${{ steps.validate.outputs.error_count }}
    
    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4
      
      - name: "Configuration Python 3.11"
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: "Téléchargement de l'artefact à valider"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artefact_recommandations }}
          path: ./validation-input/
      
      - name: "Exécution de la validation de l'artefact Markdown"
        id: validate
        run: |
          echo "🔍 Validation de l'artefact Markdown recommandations"
          
          if python .github/scripts/qualiticien_validation_artefact.py \
            --artefact "./validation-input/${{ inputs.artefact_recommandations }}" \
            --type-attendu "markdown" \
            --taille-min ${{ inputs.taille_minimale }} \
            --lignes-min 3; then
            
            echo "validation_success=true" >> $GITHUB_OUTPUT
            echo "error_count=0" >> $GITHUB_OUTPUT
            echo "✅ VALIDATION RÉUSSIE"
          else
            echo "validation_success=false" >> $GITHUB_OUTPUT
            echo "error_count=1" >> $GITHUB_OUTPUT
            echo "❌ VALIDATION ÉCHOUÉE"
            exit 1
          fi
      
      - name: "Validation spécifique du contenu recommandations"
        if: steps.validate.outputs.validation_success == 'true'
        run: |
          echo "📝 Validation du contenu spécifique des recommandations"
          
          # Vérification du contenu des recommandations
          python -c "import re; import sys; ; try:; with open('./validation-input/${{ inputs.artefact_recommandations }}', 'r', encoding='utf-8') as f:; content = f.read(); ; if not content.strip():; print('❌ ERREUR: Fichier de recommandations vide'); sys.exit(1); ; lines = content.split('\n'); print(f'📊 Lignes totales: {len(lines)}'); ; # Recherche d'éléments caractéristiques d'un rapport de recommandations; indicators = {; 'headers': len(re.findall(r'^#+\s', content, re.MULTILINE)),; 'lists': len(re.findall(r'^\s*[-*+]\s', content, re.MULTILINE)),; 'numbered_lists': len(re.findall(r'^\s*\d+\.\s', content, re.MULTILINE)),; 'recommendations': len(re.findall(r'recommand|conseil|suggest|améliorer|corriger', content, re.IGNORECASE)),; 'priorities': len(re.findall(r'priorité|urgent|important|critique|faible', content, re.IGNORECASE)),; 'actions': len(re.findall(r'action|étape|mesure|implémenter', content, re.IGNORECASE)); }; ; print(f'🔍 Éléments détectés:'); for key, count in indicators.items():; print(f'   • {key}: {count}'); ; # Validation de la structure attendue; warnings = []; ; if indicators['headers'] == 0:; warnings.append('Aucun titre détecté (# Titre)'); ; if indicators['recommendations'] == 0:; warnings.append('Aucun terme de recommandation détecté'); ; if indicators['lists'] + indicators['numbered_lists'] == 0:; warnings.append('Aucune liste détectée (structure peu organisée)'); ; if warnings:; print('⚠️  Avertissements de structure:'); for warning in warnings:; print(f'   • {warning}'); print('ℹ️  Ces avertissements ne bloquent pas la validation'); else:; print('✅ Structure des recommandations conforme'); ; # Calcul de quelques métriques; word_count = len(content.split()); char_count = len(content); ; print(f'📈 Métriques du rapport:'); print(f'   • Mots: {word_count}'); print(f'   • Caractères: {char_count}'); ; if word_count < 20:; print('⚠️  Rapport très court (< 20 mots)'); elif word_count > 1000:; print('📚 Rapport détaillé (> 1000 mots)'); else:; print('✅ Taille de rapport appropriée'); ; except Exception as e:; print(f'⚠️  Erreur validation contenu recommandations: {e}'); "
          echo "✅ Validation contenu recommandations terminée"
