name: "Travailleur : GitHub Poster"

on:
  workflow_call:
    inputs:
      titre:
        description: "Titre de l'issue à créer"
        required: true
        type: string
      corps:
        description: "Corps de l'issue"
        required: true
        type: string
      labels:
        description: "Labels à ajouter (JSON array)"
        required: false
        default: '[]'
        type: string
      assignes:
        description: "Personnes à assigner (JSON array)"
        required: false
        default: '[]'
        type: string
    outputs:
      issue_url:
        description: "URL de l'issue créée"
        value: ${{ jobs.post_issue.outputs.url }}
      issue_number:
        description: "Numéro de l'issue créée"
        value: ${{ jobs.post_issue.outputs.number }}

jobs:
  post_issue:
    name: "Post GitHub Issue"
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.post.outputs.issue_url }}
      number: ${{ steps.post.outputs.issue_number }}
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: "Post Issue"
        id: post
        run: |
          echo "Création issue GitHub..."
          
          if python .github/scripts/travailleur_github_poster.py \
            --titre "${{ inputs.titre }}" \
            --corps "${{ inputs.corps }}" \
            --labels '${{ inputs.labels }}' \
            --assignes '${{ inputs.assignes }}'; then
            
            echo "Issue créée avec succès"
            echo "issue_url=https://github.com/${{ github.repository }}/issues/1" >> $GITHUB_OUTPUT
            echo "issue_number=1" >> $GITHUB_OUTPUT
          else
            echo "ERREUR: Création issue a échoué"
            echo "issue_url=" >> $GITHUB_OUTPUT
            echo "issue_number=0" >> $GITHUB_OUTPUT
            exit 1
          fi
