name: "Travailleur : AST Parser"

on:
  workflow_call:
    inputs:
      contenu_fichier_python:
        description: "Contenu du fichier Python à parser"
        required: true
        type: string
      nom_artefact:
        description: "Nom de l'artefact de sortie"
        required: false
        default: "arbre-syntaxe.json"
        type: string
    outputs:
      nodes_found:
        description: "Nombre de noeuds AST trouvés"
        value: ${{ jobs.parse_ast.outputs.count }}
      artefact_path:
        description: "Chemin vers l'artefact"
        value: ${{ jobs.parse_ast.outputs.artifact_path }}

jobs:
  parse_ast:
    name: "Parse AST Python"
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.parse.outputs.node_count }}
      artifact_path: ${{ steps.parse.outputs.artifact_path }}
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: "Parse AST"
        id: parse
        run: |
          echo "Parsing AST Python..."
          
          if python .github/scripts/travailleur_ast_parser.py \
            --contenu "${{ inputs.contenu_fichier_python }}" \
            --output "${{ inputs.nom_artefact }}"; then
            
            echo "AST parsing réussi"
            
            if [ -f "${{ inputs.nom_artefact }}" ]; then
              node_count=$(jq -r '.nodes | length' "${{ inputs.nom_artefact }}" 2>/dev/null || echo "0")
              
              echo "node_count=$node_count" >> $GITHUB_OUTPUT
              echo "artifact_path=${{ inputs.nom_artefact }}" >> $GITHUB_OUTPUT
              
              echo "AST parsé - $node_count noeuds trouvés"
            else
              echo "ERREUR: Artefact AST non créé"
              echo "node_count=0" >> $GITHUB_OUTPUT
              exit 1
            fi
          else
            echo "ERREUR: Script AST parser a échoué"
            echo "node_count=0" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - name: "Upload artefact"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.nom_artefact }}
          path: ${{ inputs.nom_artefact }}
          retention-days: 30
