name: "🔍 NIVEAU 2 : Général Auditeur - Audit de Solution"
run-name: "🔍 Auditeur - Qualification Complète de Solution"

on:
  workflow_call:
    inputs:
      solution_a_auditer:
        description: "Solution à auditer"
        required: true
        type: string
      niveau_confiance_requis:
        description: "Niveau de confiance requis (0-100)"
        required: false
        default: 80
        type: number

    outputs:
      audit_reussi:
        description: "Audit réussi"
        value: ${{ jobs.valider_plan.outputs.validation_reussie == 'true' }}
      score_confiance:
        description: "Score de confiance final"
        value: ${{ jobs.plan_implementation.outputs.score_final }}
      plan_implementation:
        description: "Plan d'implémentation"
        value: ${{ jobs.plan_implementation.outputs.plan_json }}

jobs:
  # ÉTAPE 1: Audit du schéma (Niveau 4 - Ouvrier 1)
  audit_schema:
    name: "📋 Audit Schéma"
    uses: ./.github/workflows/04-01-auditeur-schema.yml
    with:
      solution_input: ${{ inputs.solution_a_auditer }}
      schema_requis: "solution-standard-v1"
      validation_stricte: true

  # ÉTAPE 2: Valider schéma (Niveau 5 - Qualiticien 1)
  valider_schema:
    name: "✅ Valider Schéma"
    needs: audit_schema
    uses: ./.github/workflows/05-01-auditeur-valid-schema.yml
    with:
      rapport_schema: ${{ needs.audit_schema.outputs.rapport_validation }}
      schema_attendu: "rapport-schema-v1"

  # ÉTAPE 3: Audit sécurité (Niveau 4 - Ouvrier 2)
  audit_securite_solution:
    name: "🛡️ Audit Sécurité Solution"
    needs: [audit_schema, valider_schema]
    if: needs.valider_schema.outputs.validation_reussie == 'true'
    uses: ./.github/workflows/04-02-auditeur-securite.yml
    with:
      solution_validee: ${{ needs.audit_schema.outputs.solution_normalisee }}
      niveau_analyse: "approfondi"
      tests_penetration: true

  # ÉTAPE 4: Valider sécurité (Niveau 5 - Qualiticien 2)
  valider_securite:
    name: "✅ Valider Sécurité"
    needs: audit_securite_solution
    uses: ./.github/workflows/05-02-auditeur-valid-securite.yml
    with:
      rapport_securite: ${{ needs.audit_securite_solution.outputs.analyse_securite }}
      schema_attendu: "rapport-securite-v1"

  # ÉTAPE 5: Simulation (Niveau 4 - Ouvrier 3)
  simulation_solution:
    name: "🧪 Simulation Solution"
    needs: [audit_securite_solution, valider_securite]
    if: needs.valider_securite.outputs.validation_reussie == 'true'
    uses: ./.github/workflows/04-03-auditeur-simulation.yml
    with:
      solution_securisee: ${{ needs.audit_securite_solution.outputs.solution_securisee }}
      scenarios_test: "nominal,degraded,extreme"
      duree_simulation: "300"

  # ÉTAPE 6: Valider simulation (Niveau 5 - Qualiticien 3)
  valider_simulation:
    name: "✅ Valider Simulation"
    needs: simulation_solution
    uses: ./.github/workflows/05-03-auditeur-valid-simulation.yml
    with:
      resultats_simulation: ${{ needs.simulation_solution.outputs.resultats_complets }}
      schema_attendu: "resultats-simulation-v1"

  # ÉTAPE 7: Analyse coût (Niveau 4 - Ouvrier 4)
  analyse_cout:
    name: "💰 Analyse Coût"
    needs: [simulation_solution, valider_simulation]
    if: needs.valider_simulation.outputs.validation_reussie == 'true'
    uses: ./.github/workflows/04-04-auditeur-cout.yml
    with:
      solution_simulee: ${{ needs.simulation_solution.outputs.solution_optimisee }}
      parametres_cout: '{"ressources_cpu": true, "memoire": true, "stockage": true, "reseau": true}'
      horizon_temporel: "12_mois"

  # ÉTAPE 8: Valider coût (Niveau 5 - Qualiticien 4)
  valider_cout:
    name: "✅ Valider Coût"
    needs: analyse_cout
    uses: ./.github/workflows/05-04-auditeur-valid-cout.yml
    with:
      analyse_cout: ${{ needs.analyse_cout.outputs.estimation_detaillee }}
      schema_attendu: "analyse-cout-v1"

  # ÉTAPE 9: Plan d'implémentation (Niveau 4 - Ouvrier 5)
  plan_implementation:
    name: "📊 Plan d'Implémentation"
    needs: [analyse_cout, valider_cout]
    if: needs.valider_cout.outputs.validation_reussie == 'true'
    uses: ./.github/workflows/04-05-auditeur-plan.yml
    with:
      solution_complete: ${{ needs.analyse_cout.outputs.solution_evaluee }}
      niveau_confiance_cible: ${{ inputs.niveau_confiance_requis }}
      inclure_risques: true
      inclure_timeline: true

  # ÉTAPE 10: Valider plan (Niveau 5 - Qualiticien 5)
  valider_plan:
    name: "✅ Valider Plan Final"
    needs: plan_implementation
    uses: ./.github/workflows/05-05-auditeur-valid-plan.yml
    with:
      plan_implementation: ${{ needs.plan_implementation.outputs.plan_json }}
      schema_attendu: "plan-implementation-v1"
      verification_coherence: true

  # ÉTAPE 11: Rapport final
  rapport_final_auditeur:
    name: "📋 Rapport Final Auditeur"
    needs: [plan_implementation, valider_plan]
    if: needs.valider_plan.outputs.validation_reussie == 'true'
    runs-on: ubuntu-latest

    steps:
    - name: "📊 Synthèse Audit Solution"
      run: |
        echo "🔍 RAPPORT FINAL - AUDIT DE SOLUTION"
        echo "===================================="
        echo "Score de confiance: ${{ needs.plan_implementation.outputs.score_final }}%"
        echo "Seuil requis: ${{ inputs.niveau_confiance_requis }}%"
        echo "Statut: $([ '${{ needs.plan_implementation.outputs.score_final }}' -ge '${{ inputs.niveau_confiance_requis }}' ] && echo 'CONFORME ✅' || echo 'NON CONFORME ❌')"
        echo ""
        echo "Étapes validées:"
        echo "- Schéma: ${{ needs.valider_schema.outputs.validation_reussie }}"
        echo "- Sécurité: ${{ needs.valider_securite.outputs.validation_reussie }}"
        echo "- Simulation: ${{ needs.valider_simulation.outputs.validation_reussie }}"
        echo "- Coût: ${{ needs.valider_cout.outputs.validation_reussie }}"
        echo "- Plan: ${{ needs.valider_plan.outputs.validation_reussie }}"
