name: Auto Documentation
on:
  push:
    branches: [ main ]
    paths: ["docs-api/**", "eve/**/*.py"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
        
    - name: Initialize docs if needed
      run: |
        if [ ! -f "docs-api/conf.py" ]; then
          echo "📚 Initialisation nouvelle documentation"
          mkdir -p docs-api
          sphinx-quickstart -q -p "AGI-EVE" -a "Toni" --ext-autodoc --ext-viewcode docs-api/
        else
          echo "📚 Documentation existante détectée"
        fi
        
    - name: Verify Python modules
      run: |
        if [ -d "eve" ]; then
          echo "✅ Modules EVE détectés"
          find eve -name "*.py" | head -5
        else
          echo "⚠️ Aucun module EVE trouvé"
        fi
        
    - name: Build documentation
      run: |
        cd docs
        make clean || true
        make html
        
    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-api/_build/html
