name: EVE - Neuron 1 Validation Workflow

# Déclenchement du workflow :
# - Lors d'un push sur la branche test/eve1neurone
# - Manuellement via l'interface GitHub Actions (workflow_dispatch)
on:
  push:
    branches:
      - test/eve1neurone
  workflow_dispatch:

jobs:
  validate_neuron_1:
    name: Valider le Premier Neurone d'EVE
    runs-on: ubuntu-latest # Environnement d'exécution
    timeout-minutes: 45    # Temps maximal d'exécution pour éviter les boucles (ajustable)

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4 # Utilisation de la version v4 comme convenu

      - name: Configuration de Python
        uses: actions/setup-python@v5 # Utilisation de v5 si disponible, sinon v4
        with:
          python-version: '3.10' # Assurez-vous que c'est la version compatible avec votre projet

      - name: Installation des dépendances Python (Neurone 1)
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install tensorflow # Ou pytorch si vous utilisez PyTorch (à choisir)
          pip install scikit-learn
          pip install pytest
          pip install black isort flake8

      - name: Vérification du formatage du code avec Black
        run: black --check eve_project/cognitive/neuron1/ # Assurez-vous du chemin réel du neurone

      - name: Vérification de l'ordre des imports avec Isort
        run: isort --check-only eve_project/cognitive/neuron1/

      - name: Analyse statique du code avec Flake8
        run: flake8 eve_project/cognitive/neuron1/

      - name: Exécution des Tests Unitaires pour Neurone 1
        run: |
          pytest eve_project/tests/cognitive/neuron1/
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Validation du Comportement Basique du Neurone (PoC)
        run: python eve_project/scripts/neuron1_poc_validation.py
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Collecte et Téléchargement des Artifacts (Logs de Test, Métriques)
        uses: actions/upload-artifact@v4
        with:
          name: eve-neuron1-validation-artifacts
          path: |
            # Vous pouvez ajouter ici des chemins vers des rapports ou des logs générés par pytest ou le script PoC
            # Par exemple:
            # eve_project/tests/cognitive/neuron1/pytest_report.xml
            # eve_project/logs/neuron1_validation.log
