name: "Test Orchestre + ENV"
on:
  workflow_dispatch:

env:
  CONSTITUTION_FILE: "iaGOD.json"
  AUDIT_ID: ${{ github.run_id }}-${{ github.run_attempt }}
  PARALLEL_LIMIT: 8
  TIMEOUT_CONSTITUTION: 5
  TIMEOUT_GENERAL: 30
  TIMEOUT_SYNTHESIS: 15
  ORCHESTRATEUR_VERSION: "1.0.0"

jobs:
  test_constitution:
    name: "Test Constitution avec ENV"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Test avec variables"
      run: |
        echo "AUDIT_ID: ${{ env.AUDIT_ID }}"
        echo "Constitution: ${{ env.CONSTITUTION_FILE }}"
        echo "Test réussi avec variables ENV"
