name: 📦 Package Release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Verify package structure
      run: |
        if [ ! -f "setup.py" ] && [ ! -f "pyproject.toml" ]; then
          echo "❌ Erreur: setup.py ou pyproject.toml requis pour package"
          exit 1
        fi
        echo "✅ Structure package validée"
        
    - name: Install build dependencies
      run: |
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Verify build
      run: |
        if [ ! -d "dist" ] || [ -z "$(ls -A dist/)" ]; then
          echo "❌ Erreur: Build échoué, aucun package généré"
          exit 1
        fi
        echo "✅ Package généré avec succès"
        ls -la dist/
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
