name: Parallel Development Monitor

on:
  push:
    branches: [ agi-main, eve-main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  monitor-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Monitor Branch Divergence
      run: |
        echo "📊 Monitoring parallel development AGI/EVE"
        
        # Comparer les branches
        git diff --stat agi-main eve-main > branch_diff.txt || echo "Branches différentes (normal)"
        
        # Statistiques commits
        AGI_COMMITS=$(git rev-list --count agi-main)
        EVE_COMMITS=$(git rev-list --count eve-main)
        
        echo "AGI commits: $AGI_COMMITS"
        echo "EVE commits: $EVE_COMMITS"
        echo "Divergence tracking: OK"
    
    - name: Upload Branch Status
      uses: actions/upload-artifact@v4
      with:
        name: parallel-development-status
        path: branch_diff.txt
