name: Performance & Benchmarks

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 4 * * *'  # Quotidien à 4h

jobs:
  performance-tests:
    name: Performance Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install performance tools
      run: |
        pip install pytest-benchmark memory-profiler line-profiler
        pip install psutil py-spy
        
    - name: Verify test structure
      run: |
        echo "🔍 VÉRIFICATION STRUCTURE TESTS"
        echo "==============================="
        
        if [ ! -d "tests" ]; then
          echo "📁 Création dossier tests/"
          mkdir -p tests/benchmarks
        fi
        
        if [ ! -d "tests/benchmarks" ]; then
          echo "📁 Création dossier tests/benchmarks/"
          mkdir -p tests/benchmarks
        fi
        
        # Créer test benchmark basique si absent
        if [ ! -f "tests/benchmarks/test_basic_performance.py" ]; then
          echo "📝 Création test benchmark basique"
          cat > tests/benchmarks/test_basic_performance.py << 'PYTEST'
import time
import pytest

def slow_function():
    """Fonction test pour benchmark"""
    time.sleep(0.01)
    return sum(range(1000))

def test_performance_basic(benchmark):
    """Test performance basique"""
    result = benchmark(slow_function)
    assert result > 0

def test_list_comprehension(benchmark):
    """Test performance list comprehension"""
    result = benchmark(lambda: [x*2 for x in range(1000)])
    assert len(result) == 1000
PYTEST
        fi
        
    - name: Find main entry point
      id: main_file
      run: |
        echo "🔍 RECHERCHE POINT D'ENTRÉE PRINCIPAL"
        echo "===================================="
        
        # Chercher fichiers principaux possibles
        if [ -f "main.py" ]; then
          echo "main_file=main.py" >> $GITHUB_OUTPUT
          echo "✅ Trouvé: main.py"
        elif [ -f "core/main.py" ]; then
          echo "main_file=core/main.py" >> $GITHUB_OUTPUT
          echo "✅ Trouvé: core/main.py"
        elif [ -f "run_agi_audit.py" ]; then
          echo "main_file=run_agi_audit.py" >> $GITHUB_OUTPUT
          echo "✅ Trouvé: run_agi_audit.py"
        else
          echo "main_file=none" >> $GITHUB_OUTPUT
          echo "⚠️ Aucun fichier principal trouvé"
          echo "Création script test minimal"
          cat > performance_test.py << 'PYTHON'
def main():
    """Script test pour profiling"""
    result = sum(x*x for x in range(10000))
    print(f"Performance test result: {result}")
    return result

if __name__ == "__main__":
    main()
PYTHON
          echo "main_file=performance_test.py" >> $GITHUB_OUTPUT
        fi
        
    - name: Run benchmark tests
      run: |
        echo "🏃 EXÉCUTION TESTS BENCHMARK"
        echo "============================"
        
        if [ -d "tests/benchmarks" ] && [ "$(ls -A tests/benchmarks)" ]; then
          pytest tests/benchmarks/ --benchmark-json=benchmark-results.json -v
        else
          echo "⚠️ Aucun test benchmark disponible"
          echo '{"benchmarks": [], "note": "no tests available"}' > benchmark-results.json
        fi
        
    - name: Memory profiling
      if: steps.main_file.outputs.main_file != 'none'
      run: |
        echo "🧠 PROFILING MÉMOIRE"
        echo "==================="
        
        python -m memory_profiler ${{ steps.main_file.outputs.main_file }} > memory-profile.txt 2>&1 || echo "Memory profiling terminé avec avertissements"
        
    - name: CPU profiling  
      if: steps.main_file.outputs.main_file != 'none'
      run: |
        echo "⚡ PROFILING CPU"
        echo "==============="
        
        python -m cProfile -o cpu-profile.prof ${{ steps.main_file.outputs.main_file }} 2>&1 || echo "CPU profiling terminé avec avertissements"
        
    - name: Performance summary
      run: |
        echo "📊 RÉSUMÉ PERFORMANCE"
        echo "===================="
        
        if [ -f "benchmark-results.json" ]; then
          echo "✅ Benchmarks générés"
        fi
        
        if [ -f "memory-profile.txt" ]; then
          echo "✅ Profil mémoire généré"
          echo "Taille: $(wc -l < memory-profile.txt) lignes"
        fi
        
        if [ -f "cpu-profile.prof" ]; then
          echo "✅ Profil CPU généré"
        fi
        
    - name: Archive performance results
      uses: actions/upload-artifact@v4
      with:
        name: performance-reports
        path: |
          benchmark-results.json
          memory-profile.txt
          cpu-profile.prof
          performance_test.py
