name: Advanced Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Tous les lundis à 2h

jobs:
  security-scan:
    name: Multi-Tool Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        
    - name: Install security tools
      run: |
        pip install bandit semgrep safety pip-audit
        npm install -g audit-ci || echo "npm not available"
        
    - name: Run Bandit (Python security)
      run: |
        bandit -r . -f json -o bandit-results.json
        bandit -r . -f txt
        
    - name: Run Semgrep
      run: |
        python -m semgrep --config=auto --json --output=semgrep-results.json .
        
    - name: Dependency vulnerability scan
      run: |
        safety check --json --output safety-results.json || echo "Safety check completed"
        pip-audit --format=json --output=pip-audit-results.json || echo "Pip audit completed"
        
    - name: Upload security results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep-results.json
      continue-on-error: true
      
    - name: Archive security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          *-results.json
          *.log
