# .github/workflows/stimulate_neuron.yml
name: "Test Simple Neurone Dispatch" # Nouveau nom pour forcer l'indexation

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Un message de test minimal"
        required: true
        type: string
        default: "Test minimal réussi !"

jobs:
  simple_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Afficher le message de test"
        run: echo "Message reçu : ${{ inputs.message }}"
