# .github/workflows/stimulate_neuron.yml
name: "Stimulateur de Neurone"

on:
  workflow_dispatch: # Permet de déclencher manuellement le workflow depuis l'interface GitHub
    inputs:
      neuron_target_id:
        description: "ID du neurone à stimuler"
        required: true
        type: string
        default: "001"
      stimulus:
        description: "Force du stimulus (0.0 à 1.0)"
        required: true
        type: number
        default: 0.6

jobs:
  send_stimulus:
    runs-on: ubuntu-latest
    steps:
      - name: "Appeler le neurone"
        uses: ./.github/workflows/quasi_neuron.yml # Chemin vers votre workflow neurone
        with:
          neuron_id: ${{ inputs.neuron_target_id }}
          stimulus_strength: ${{ inputs.stimulus }}
        id: neuron_response

      - name: "Afficher la réponse du neurone"
        run: |
          echo "Le neurone ${{ inputs.neuron_target_id }} a répondu :"
          echo "  A tiré une impulsion : ${{ steps.neuron_response.outputs.neuron_fired }}"
          echo "  Potentiel actuel : ${{ steps.neuron_response.outputs.current_potential }}"
          echo "  Nouveau poids synaptique : ${{ steps.neuron_response.outputs.new_synaptic_weight }}"
          echo "  Temps réfractaire restant : ${{ steps.neuron_response.outputs.refractory_countdown }}"
